name: app_distribution

on:
  push:
    branches: [ main, develop, epic/** ]
  workflow_dispatch:
jobs:
  build:
    name: app_publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build release AAB
        run: ./gradlew bundleRelease

      - name: Set Firebase tester group
        id: tester_group
        run: |
            if [[ "${{ github.ref_name }}" == "main" ]]; then
              echo "group=${{ secrets.TESTERS_RELEASE }}" >> $GITHUB_OUTPUT
            elif [[ "${{ github.ref_name }}" == "develop" ]]; then
              echo "group=${{ secrets.TESTERS_RELEASE }}" >> $GITHUB_OUTPUT
            else
              echo "group=${{ secrets.TESTERS_BETA }}" >> $GITHUB_OUTPUT
            fi
      - name: Upload APK using Firebase CLI
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute \
          app/build/outputs/bundle/release/app-release.aab \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --token ${{ secrets.FIREBASE_TOKEN }} \
          --groups "${{ steps.tester_group.outputs.group }}" \
          --release-notes "CI upload using auth token"