name: app_distribution

on:
  push:
    branches: [ main, develop, epic/** ]
  workflow_dispatch:
jobs:
  build:
    name: app_publish
    runs-on: ubuntu-latest
    env:
      GITHUB_REF_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Restore google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > app/google-services.json

      - name: Restore keys.properties
        run: |
          echo "${{ secrets.API_KEYS_FILE }}" > local.properties

      - name: Restore firebase_release_key
        run: |
          echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 --decode > > firebase_release_key.jks    

      - name: Build release AAB
        run: ./gradlew bundleRelease

      - name: Set Firebase tester group
        id: tester_group
        run: |
          if [[ "$GITHUB_REF_NAME" == "main" || "$GITHUB_REF_NAME" == "develop" ]]; then
            echo "group=${{ secrets.TESTERS_RELEASE }}" >> "$GITHUB_OUTPUT"
          else
            echo "group=${{ secrets.TESTERS_BETA }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload APK using Firebase CLI
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute \
          app/build/outputs/bundle/release/app-release.aab \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --token ${{ secrets.FIREBASE_TOKEN }} \
          --groups "${{ steps.tester_group.outputs.group }}" \
          --release-notes "CI upload using auth token"